# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "metachannels-api-client"
  s.version = "0.6.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alex Soto"]
  s.date = "2012-08-10"
  s.description = "A gem to consume the metachannels-api.  See http://support.metachannels.com/forums/202518-metachannels-api "
  s.email = "support@metachannels.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rvmrc",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/metachannels-api-client.rb",
    "metachannels-api-client.gemspec",
    "spec/metachannels-api-client_spec.rb",
    "spec/spec_helper.rb",
    "test/helper.rb"
  ]
  s.homepage = "http://github.com/channels/metachannels-api-client"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "Gem to consume the metachannels.com api"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<wrest>, ["~> 1.4.7"])
      s.add_runtime_dependency(%q<rake>, [">= 0"])
      s.add_runtime_dependency(%q<i18n>, ["~> 0.6"])
      s.add_development_dependency(%q<jeweler>, ["~> 1"])
      s.add_development_dependency(%q<rspec>, ["~> 2"])
      s.add_runtime_dependency(%q<wrest>, ["~> 1.4.7"])
    else
      s.add_dependency(%q<wrest>, ["~> 1.4.7"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<i18n>, ["~> 0.6"])
      s.add_dependency(%q<jeweler>, ["~> 1"])
      s.add_dependency(%q<rspec>, ["~> 2"])
      s.add_dependency(%q<wrest>, ["~> 1.4.7"])
    end
  else
    s.add_dependency(%q<wrest>, ["~> 1.4.7"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<i18n>, ["~> 0.6"])
    s.add_dependency(%q<jeweler>, ["~> 1"])
    s.add_dependency(%q<rspec>, ["~> 2"])
    s.add_dependency(%q<wrest>, ["~> 1.4.7"])
  end
end

